# This is a config for E2B sandbox template.
# You can use template ID (blznvycsfljpbiiz8f2r) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("blznvycsfljpbiiz8f2r") # Sync sandbox
# sandbox = await AsyncSandbox.create("blznvycsfljpbiiz8f2r") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('blznvycsfljpbiiz8f2r')

team_id = "865ed723-bb56-4321-ad57-67cfbcd18e4a"
start_cmd = "npm run dev"
dockerfile = "e2b.Dockerfile"
template_id = "blznvycsfljpbiiz8f2r"
